### ISSUE TITLE
Consider using the API instead of scraping?

### ISSUE THREAD

**Issue by jlivni** [cmfatih/publicalerts#1]
Hi there,

I work on the Google Crisis Response team, which is responsible for the public alerts site this module makes use of.

If you're willing to share, I'm curious to hear more about your use case for public alerts, and whether you'd be interested in testing out our API [(demo here)](http://crisis-demos.appspot.com/alerts).

**Comment by devfacet** [comment]
Hi @jlivni 

Honestly I developed this module for contributing open source community and I don't use myself. I just want to make this **important** public information is more accessible for the open source community.

I would like to look at that API if it provides better information/speed. But I'm little bit busy nowadays so pull requests are welcome :)

P.S.: I can add you to the contributors list ( as well as https://www.npmjs.org/package/publicalerts ) if you want to implement it to this module. Otherwise I will look at it maybe next month.

**Comment by jlivni** [comment]
Thanks for the reply Fatih, and for creating the module (we also think the
public alerts information is important!).

The API is still in a trusted tester phase and using it requires getting
whitelisted.  Therefore it may not be a perfect for for this module quite
yet (since it would also require anyone who wanted to fork it and use it
themselves get whitelisted).  So I was mostly curious to get feedback from
developers who were using the public alerts in this early stage.

When The API is publicly released I'll try remember to create a pull
request here, and meanwhile please let me know if you'd like to play with
it if you find a direct use for yourself.

**Comment by devfacet** [comment]
Sounds good to me. I will definitely let you know when I have a time for it. Thanks for your work and contributions to the public. :)

**Comment by devfacet** [comment]
@jlivni : Is the API publicly released?

**Comment by jlivni** [comment]
No, it's still in a trusted tester mode.  I'm happy to provide you with access if you'd like to use it however.

**Comment by devfacet** [comment]
@jlivni : sure... my email address can be found at https://www.npmjs.com/~cmfatih

I'm thinking to create a branch in this repo and merge it when the API became public.

**Comment by stephenyeargin** [comment]
Quick note that this module has stopped working. I've [applied for access](http://crisis-demos.appspot.com/contact) to the API and would be willing to refactor this module to work with the API.

Going to open a separate Issue on the repository for tracking that.
